spring.application.name=forum-hub

spring.datasource.url=${DB_FORUM_HUB_URL}
spring.datasource.username=${DB_FORUM_HUB_USER}
spring.datasource.password=${DB_FORUM_HUB_PASSWORD}

spring.flyway.enabled=true


server.error.include-stacktrace=never

api.security.token.secret=${JWT_FORUM_HUB_SECRET}
